### PR TITLE
fixed 'gridWidth' bug

### PR DESCRIPTION
**Pull request by mrtanweijie**

### CODE REVIEW

**Comment by euvl** [comment]
What was the bug ? 😄

**Comment by mrtanweijie** [comment]
I found `gridResponsiveWidth` never been used in the code .  So when I use the `gridWidth ` it did not effective ,  the value of `rowCount` ( and `rowShift`) still count by the `windowWidth` 😄

**Comment by euvl** [comment]
Cool, great work!

**Comment by euvl** [comment]
I ll test it on the weekends tho

**Pull request merged**
